name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f ./windows/Dockerfile -t pyinstaller-windows .

      - name: Create dist directory
        run: mkdir windows\dist

      - name: Run Docker container
        run: docker run --rm -v "${{ github.workspace }}\windows\dist:C:\dist" pyinstaller-windows powershell -Command "pyinstaller main.py --name minecraft-mods-localizer-windows-${{ github.ref_name }} --onedir --onefile --clean --console --distpath C:\dist --workpath C:\build --specpath C:\"
